# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clip.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(853, 551)
        self.Path_but = QtWidgets.QPushButton(Form)
        self.Path_but.setGeometry(QtCore.QRect(20, 480, 141, 28))
        self.Path_but.setObjectName("Path_but")
        self.define_but = QtWidgets.QPushButton(Form)
        self.define_but.setGeometry(QtCore.QRect(620, 480, 81, 31))
        self.define_but.setObjectName("define_but")
        self.btn_pause = QtWidgets.QPushButton(Form)
        self.btn_pause.setGeometry(QtCore.QRect(310, 480, 93, 31))
        self.btn_pause.setObjectName("btn_pause")
        self.input_time = QtWidgets.QLineEdit(Form)
        self.input_time.setGeometry(QtCore.QRect(620, 420, 151, 31))
        self.input_time.setObjectName("input_time")
        self.clip_but = QtWidgets.QPushButton(Form)
        self.clip_but.setGeometry(QtCore.QRect(430, 480, 93, 31))
        self.clip_but.setObjectName("clip_but")
        self.video_lab = QtWidgets.QLabel(Form)
        self.video_lab.setGeometry(QtCore.QRect(10, 30, 591, 431))
        self.video_lab.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.video_lab.setText("")
        self.video_lab.setObjectName("video_lab")
        self.clip_lab = QtWidgets.QLabel(Form)
        self.clip_lab.setGeometry(QtCore.QRect(620, 30, 191, 31))
        self.clip_lab.setStyleSheet("")
        self.clip_lab.setText("")
        self.clip_lab.setObjectName("clip_lab")
        self.save_but = QtWidgets.QPushButton(Form)
        self.save_but.setGeometry(QtCore.QRect(170, 480, 111, 31))
        self.save_but.setObjectName("save_but")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Path_but.setText(_translate("Form", "选择视频文件"))
        self.define_but.setText(_translate("Form", "确认"))
        self.btn_pause.setText(_translate("Form", "播放"))
        self.clip_but.setText(_translate("Form", "截取"))
        self.save_but.setText(_translate("Form", "选择保存文件"))
